image: Visual Studio 2019
install:
  git submodule update --init --recursive
build:
  project: build/downloadunzip.sln
after_build:
  7z a downloadunzip.zip build\out\$(configuration)\downloadunzip\downloadunzip.exe
  7z a downloadunzip.zip build\out\$(configuration)\downloadunzip\downloadunzip.pdb
artifacts:
  path: downloadunzip.zip
