image: Visual Studio 2019
install:
  git submodule update --init --recursive
platform: x64
configuration: Release
build:
  project: build/downloadunzip.sln
after_build:
  - cmd: 7z a downloadunzip_x64.zip %APPVEYOR_BUILD_FOLDER%\build\out\x64\Release\downloadunzip\downloadunzip.exe
  - cmd: 7z a downloadunzip_x64.zip %APPVEYOR_BUILD_FOLDER%\build\out\x64\Release\downloadunzip\downloadunzip.pdb
artifacts:
  path: downloadunzip_x64.zip
deploy:
  provider: GitHub
  description: 'TODO: release description'
  auth_token:
    secure: 1IOzKBPzdXZG2oZzT7aNYY2iAfo+uD3d+yTIHBFQYw+J3yXAg9s9VbR6j32gORps
  artifact: downloadunzip_x64.zip
  draft: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
